# Generated by Django 6.0.2 on 2026-02-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('ciudad', models.CharField(default='Asunción', max_length=255)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
            ],
        ),
    ]
