# Generated by Django 6.0.2 on 2026-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo', models.IntegerField()),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_credito', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
