# Generated by Django 6.0.2 on 2026-03-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='barrio',
            field=models.CharField(default='No especificado', max_length=255),
        ),
    ]
